#!/usr/bin/env bash
# Script that configure HAproxy on your lb-01 server.

apt-get update
apt-get install -y haproxy
cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.default
echo "
listen 29847-lb-01
	bind *:80
	mode http
	balance roundrobin
	option httpclose
	option forwardfor
	server 29847-web-01 44.192.68.9:80 check
	server 29847-web-02 35.174.208.90:80 check
" >> /etc/haproxy/haproxy.cfg
service haproxy restart
